//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odev2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        public int KitapID { get; set; }
        public string KitapAdi { get; set; }
        public string KitapSeriNo { get; set; }
        public string Kategori { get; set; }
        public string YazarAdi { get; set; }
        public int SatisFiyati { get; set; }
        public bool StokDurum { get; set; }
    }
}
